### ISSUE TITLE
Crash when building the Advanced Large Miner

### ISSUE THREAD

**Issue by HoleFish** [huneau/gregicality#1]
[crash-2020-04-12_12.28.46-server.txt](https://github.com/huneau/gregic-additions-rework/files/4466199/crash-2020-04-12_12.28.46-server.txt)

And a suggestion: add config to tweak and ban the machines, multiblocks and other things

**Comment by HoleFish** [comment]
This mod seems to aim at being 1.12.2 gt++ , well

**Comment by huneau** [comment]
@HoleFish thx for using it :)
I see the issue... Fix on the next release.

**Comment by HoleFish** [comment]
@huneau I think this bug may appear on other multiblock, better check all of them.

**Comment by huneau** [comment]
done on the last release

**Comment by HoleFish** [comment]
May I ask, have you got the permission from alkcorp or bartimaeusnek? I don't want to see a perfect mod fail for plagiarism.

**Comment by huneau** [comment]
bartimaeusnek is MIT and dont use anything from GT++.
