### ISSUE TITLE
Crash with NPutils

### ISSUE THREAD

**Issue by brachy84** [huneau/gregicality#2]
crash on startup. also have ceu installed and some other mods
https://hastebin.com/kiyazoqifi.coffeescript

**Comment by huneau** [comment]
Hello, thx of using my mod. 
I'm sorry, but I'm not compatible with NPU and CEU.

**Comment by huneau** [comment]
@brachy84 If you need NPU Tell me what feature you want and I will add it :)

**Comment by brachy84** [comment]
So I removed NPU and CEU. And I I'm blown away about how much more there is than in NPU. Seriously Npu is nothing compared to this. I opened another issue for a few bugs i found.
