### ISSUE TITLE
Crash Minecraft 

### ISSUE THREAD

**Issue by Rotoff5362** [huneau/gregicality#21]
the world doesn't load when loading
Version mod (Gregic_Additions_Rework-1.12.2-0.12.4)

Hello can the world be saved?

---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  Thaumic Augmentation Core Plugin (ThaumicAugmentation-1.12.2-1.1.17.jar)
  AstralCore (astralsorcery-1.12.2-1.10.23.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.262.jar)
  BewitchmentFMLLoadingPlugin (bewitchment-1.12.2-0.0.21.11.jar)
  GTCELoadingPlugin (gregtech-1.12.2-1.9.0.481.jar)
  HCASM (HammerLib-1.12.2-2.0.6.14.jar)
  TLSkinCapeHookLoader (tlskincape_1.12.2-1.4.jar)
  CoreMod (Aroma1997Core_1.12.2_2.0.0.2.jar)
Contact their authors BEFORE contacting forge

// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 5/1/20 8:41 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at gregicadditions.machines.multi.MetaTileEntityIndustrialPrimitiveBlastFurnace.updateFormedValid(MetaTileEntityIndustrialPrimitiveBlastFurnace.java:107)
	at gregtech.api.metatileentity.multiblock.MultiblockControllerBase.update(MultiblockControllerBase.java:54)
	at gregtech.api.metatileentity.MetaTileEntityHolder.func_73660_a(MetaTileEntityHolder.java:155)
	at com.zeitheron.hammercore.asm.McHooks.tickTile(McHooks.java:38)
	at net.minecraft.world.World.func_72939_s(World.java:1838)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at gregicadditions.machines.multi.MetaTileEntityIndustrialPrimitiveBlastFurnace.updateFormedValid(MetaTileEntityIndustrialPrimitiveBlastFurnace.java:107)
	at gregtech.api.metatileentity.multiblock.MultiblockControllerBase.update(MultiblockControllerBase.java:54)
	at gregtech.api.metatileentity.MetaTileEntityHolder.func_73660_a(MetaTileEntityHolder.java:155)
	at com.zeitheron.hammercore.asm.McHooks.tickTile(McHooks.java:38)

-- Block entity being ticked --
Details:
	Name: gregtech:machine // gregtech.api.metatileentity.MetaTileEntityHolder
	Block type: ID #1134 (tile.unnamed // gregtech.api.block.machines.BlockMachine // gregtech:machine)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (304,70,114), Chunk: (at 0,4,2 in 19,7; contains blocks 304,0,112 to 319,255,127), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Actual block type: ID #1134 (tile.unnamed // gregtech.api.block.machines.BlockMachine // gregtech:machine)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1838)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: Новый мир
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 625 Drop: 0
	Level seed: -546627589243729876
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (228,64,256), Chunk: (at 4,4,0 in 14,16; contains blocks 224,0,256 to 239,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1326498 game time, 1998003 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 47670 (now: false), thunder time: 43419 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_251, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 5826749144 bytes (5556 MB) / 8153726976 bytes (7776 MB) up to 8388608000 bytes (8000 MB)
	JVM Flags: 8 total; -Xmn128M -Xmx8000M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_F4 53 mods loaded, 53 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                         | Version                  | Source                                        | Signature                                |
	|:------ |:-------------------------- |:------------------------ |:--------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                  | 1.12.2                   | minecraft.jar                                 | None                                     |
	| LCHIJA | mcp                        | 9.42                     | minecraft.jar                                 | None                                     |
	| LCHIJA | FML                        | 8.0.99.99                | forge-1.12.2-14.23.5.2847.jar                 | None                                     |
	| LCHIJA | forge                      | 14.23.5.2847             | forge-1.12.2-14.23.5.2847.jar                 | None                                     |
	| LCHIJA | micdoodlecore              |                          | minecraft.jar                                 | None                                     |
	| LCHIJA | guideapi                   | 1.12-2.1.8-63            | Guide-API-1.12-2.1.8-63.jar                   | None                                     |
	| LCHIJA | bloodmagic                 | 1.12.2-2.4.3-105         | BloodMagic-1.12.2-2.4.3-105 (1).jar           | None                                     |
	| LCHIJA | theoneprobe                | 1.4.28                   | theoneprobe-1.12-1.4.28.jar                   | None                                     |
	| LCHIJA | animus                     | 1                        | Animus-1.12-2.1.7.jar                         | None                                     |
	| LCHIJA | appliedenergistics2        | rv6-stable-7             | appliedenergistics2-rv6-stable-7.jar          | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| LCHIJA | aroma1997core              | 2.0.0.2                  | Aroma1997Core_1.12.2_2.0.0.2.jar              | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| LCHIJA | aromabackup                | 3.0.0.0.b113             | AromaBackup_1.12.2_3.0.0.0.b113.jar           | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| LCHIJA | aromabackuprecovery        | 3.0.0.0.b113             | AromaBackup_1.12.2_3.0.0.0.b113.jar           | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| LCHIJA | baubles                    | 1.5.2                    | Baubles-1.12-1.5.2.jar                        | None                                     |
	| LCHIJA | astralsorcery              | 1.10.22                  | astralsorcery-1.12.2-1.10.23.jar              | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
	| LCHIJA | patchouli                  | 1.0-20                   | Patchouli-1.0-20.jar                          | None                                     |
	| LCHIJA | bewitchment                | 0.21.11                  | bewitchment-1.12.2-0.0.21.11.jar              | None                                     |
	| LCHIJA | bloodarsenal               | 1.12.2-2.2.2-31          | BloodArsenal-1.12.2-2.2.2-31.jar              | None                                     |
	| LCHIJA | chameleon                  | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                      | None                                     |
	| LCHIJA | codechickenlib             | 3.2.2.353                | CodeChickenLib-1.12.2-3.2.2.353-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | hammercore                 | 2.0.6.14                 | HammerLib-1.12.2-2.0.6.14.jar                 | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
	| LCHIJA | lux                        | 12r                      | ColoredLux-1.12.2-12r.jar                     | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
	| LCHIJA | ic2                        | 2.8.197-ex112            | industrialcraft-2-2.8.197-ex112.jar           | de041f9f6187debbc77034a344134053277aa3b0 |
	| LCHIJA | thaumcraft                 | 6.1.BETA26               | Thaumcraft-1.12.2-6.1.BETA26 (1).jar          | None                                     |
	| LCHIJA | emt                        | 12.2.0                   | emt-12.2.4.jar                                | None                                     |
	| LCHIJA | extracells                 | 2.6.5                    | ExtraCells-1.12.2-2.6.5.jar                   | None                                     |
	| LCHIJA | galacticraftcore           | 4.0.2.262                | GalacticraftCore-1.12.2-4.0.2.262.jar         | None                                     |
	| LCHIJA | galacticraftplanets        | 4.0.2.262                | Galacticraft-Planets-1.12.2-4.0.2.262.jar     | None                                     |
	| LCHIJA | mjrlegendslib              | 1.12.2-1.1.9             | MJRLegendsLib-1.12.2-1.1.9.jar                | b02331787272ec3515ebe63ecdeea0d746653468 |
	| LCHIJA | extraplanets               | 1.12.2-0.6.4             | ExtraPlanets-1.12.2-0.6.4.jar                 | b02331787272ec3515ebe63ecdeea0d746653468 |
	| LCHIJA | fastleafdecay              | v14                      | FastLeafDecay-v14.jar                         | None                                     |
	| LCHIJA | jei                        | 4.15.0.293               | jei_1.12.2-4.15.0.293.jar                     | None                                     |
	| LCHIJA | forestry                   | 5.8.2.422                | forestry_1.12.2-5.8.2.422.jar                 | None                                     |
	| LCHIJA | gravisuite                 | 3.1.1                    | Gravitation+Suite-3.1.1.jar                   | None                                     |
	| LCHIJA | gregtech                   | 1.9.0.481                | gregtech-1.12.2-1.9.0.481.jar                 | None                                     |
	| LCHIJA | gtadditions                | 1.12.2-0.12.4            | Gregic_Additions_Rework-1.12.2-0.12.4.jar     | None                                     |
	| LCHIJA | inventorytweaks            | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                      | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCHIJA | jeibees                    | 0.9.0.5                  | jeibees-0.9.0.5-mc1.12.2.jar                  | None                                     |
	| LCHIJA | journeymap                 | 1.12.2-5.7.1             | journeymap-1.12.2-5.7.1.jar                   | None                                     |
	| LCHIJA | mets                       | 1.531                    | MoreElectricTools.v1.531.jar                  | None                                     |
	| LCHIJA | mutantbeasts               | 1.12.2-0.7.1             | MutantBeasts-1.12.2-0.7.1.jar                 | 25e0dcff5b5a7325d7c28898af41ff8b0ba41b77 |
	| LCHIJA | stackable                  | 1.3.3                    | stackable-1.12.2-1.3.3.jar                    | None                                     |
	| LCHIJA | storagedrawers             | 1.12.2-5.4.1             | StorageDrawers-1.12.2-5.4.1.jar               | None                                     |
	| LCHIJA | tc6aspects4jei             | 0.0.2a                   | tc6aspects4jei-0.0.2a.jar                     | None                                     |
	| LCHIJA | thaumadditions             | 12.4.2                   | ThaumicAdditions-1.12.2-12.4.2.jar            | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
	| LCHIJA | thaumicaugmentation        | 1.12.2-1.1.17            | ThaumicAugmentation-1.12.2-1.1.17.jar         | 8f678591ba6f78d579e553a8aa94b4c4766cb13d |
	| LCHIJA | thaumicjei                 | 1.6.0                    | ThaumicJEI-1.12.2-1.6.0-27.jar                | None                                     |
	| LCHIJA | thaumicenergistics         | 2.2.3                    | thaumicenergistics-2.2.4.jar                  | None                                     |
	| LCHIJA | thaumictinkerer            | 1.12.2-5.0-008333d       | thaumictinkerer-1.12.2-5.0-008333d.jar        | None                                     |
	| LCHIJA | tlauncher_custom_cape_skin | 1.4                      | tlskincape_1.12.2-1.4.jar                     | None                                     |
	| LCHIJA | topaddons                  | 1.12.2-1.13.0            | topaddons-1.12.2-1.13.0.jar                   | None                                     |
	| LCHIJA | twilightforest             | 3.10.1013                | twilightforest-1.12.2-3.10.1013-universal.jar | None                                     |
	| LCHIJA | visuals                    | 7r                       | Visuals-1.12.2-7r.jar                         | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |

	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
Thaumic Augmentation Core Plugin (ThaumicAugmentation-1.12.2-1.1.17.jar)
  thecodex6824.thaumicaugmentation.core.TATransformer
AstralCore (astralsorcery-1.12.2-1.10.23.jar)
  
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.262.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
BewitchmentFMLLoadingPlugin (bewitchment-1.12.2-0.0.21.11.jar)
  
GTCELoadingPlugin (gregtech-1.12.2-1.9.0.481.jar)
  gregtech.common.asm.GTCETransformer
HCASM (HammerLib-1.12.2-2.0.6.14.jar)
  com.zeitheron.hammercore.asm.HammerCoreTransformer
TLSkinCapeHookLoader (tlskincape_1.12.2-1.4.jar)
  gloomyfolken.hooklib.minecraft.PrimaryClassTransformer
CoreMod (Aroma1997Core_1.12.2_2.0.0.2.jar)
  
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	AE2 Version: stable rv6-stable-7 for Forge 14.23.5.2768
	HammerCore Debug Information: 
Dependent Mods:
    -Colored Lux (lux) @12r
    -Thaumic Additions: Reconstructed (thaumadditions) @12.4.2
    -Visuals (visuals) @7r

	AE2 Integration: IC2:ON, RC:OFF, MFR:OFF, Waila:OFF, InvTweaks:ON, JEI:ON, Mekanism:OFF, OpenComputers:OFF, THE_ONE_PROBE:ON, TESLA:OFF, CRAFTTWEAKER:OFF
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_F4
	OptiFine Build: 20191023-234904
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 436.30
	OpenGlRenderer: GeForce GTX 1060 6GB/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by huneau** [comment]
Hi, I see the issue. you have logged out during crafting. I will fix it.

**Comment by huneau** [comment]
the fix will be deployed in a few minutes. Sorry

**Comment by Rotoff5362** [comment]
Thanks

**Comment by Rotoff5362** [comment]
thank you, it helped
