### ISSUE TITLE
crash Server 

### ISSUE THREAD

**Issue by blakpsykozz** [huneau/gregicality#4]
hello , mod does not work on my server it crash
[crash-2020-04-21_15.29.29-server.txt](https://github.com/huneau/gregic-additions-rework/files/4510331/crash-2020-04-21_15.29.29-server.txt)

**Comment by huneau** [comment]
Hey! I see the issue. will be fix on the next release (at the end of the day)

**Comment by blakpsykozz** [comment]
hey, okay thanks ^^
