### ISSUE TITLE
The guide of The Large Circuit Assembly Line in JEI is wrong

### ISSUE THREAD

**Issue by magcicada** [huneau/gregicality#6]
The guide of The Large Circuit Assembly Line in JEI have a tiny error,the controller is incorrectly placed into an Assembly Line.

**Comment by huneau** [comment]
thank god! Looking for ages the issue.

**Comment by magcicada** [comment]
Just is the image [yerrrrrr](https://imgur.com/dxFLtxq).

**Comment by magcicada** [comment]
![20200426174400](https://user-images.githubusercontent.com/45464670/80303940-cf18f000-87e5-11ea-8313-e6e14e373019.png)

This words is hard-coded?I can't translate it.

**Comment by huneau** [comment]
yes some of the internal info is hardcoded. Sorry, will fix it right now.

**Comment by magcicada** [comment]
I am trying to translate Simplified Chinese,I will submit pr after completion.And there is also an error here, Blize is missing the key.
![20200426175147](https://user-images.githubusercontent.com/45464670/80304146-d8568c80-87e6-11ea-94f5-ff0b7bb857e0.png)

**Comment by huneau** [comment]
it's material.blizz

**Comment by huneau** [comment]
@magcicada have you see https://github.com/huneau/gregic-additions-rework/blob/master/docs/multiblock/voidminer/voidminer.md ?

**Comment by magcicada** [comment]
yes,I read it,thanks for your help.

**Comment by magcicada** [comment]
The tooltip of Alloy Blast Furnace and Chemical Plant also is hard code?I can't find the key in the en_us.lang

**Comment by magcicada** [comment]
Large Transformer,Large Rocket Engine and Alloy Blast Furnace have no recipes.

**Comment by magcicada** [comment]
High Pressure Steam has no recipe

**Comment by huneau** [comment]
high pressure is made in the nuclear reactor. but its right anywhere

**Comment by magcicada** [comment]
Large Transformer,Large Rocket Engine and Alloy Blast Furnace are unfinished work?I can't find the recipes

**Comment by huneau** [comment]
I forget, Its done. but forget recipe.... it's always a part I hate to create recipe. I prefered to make feature

**Comment by magcicada** [comment]
![20200426221730](https://user-images.githubusercontent.com/45464670/80310148-cc30f600-880b-11ea-8c33-e57bd2b3e6c4.png)
![20200426221652](https://user-images.githubusercontent.com/45464670/80310151-ce935000-880b-11ea-9ed8-00cad41b4d5c.png)
The tooltips are hard code?I can't find the key

**Comment by magcicada** [comment]
Hope you can modify these two words so that they can be translated,Simplified Chinese translation can be completed within 10%.After these two words are fixed, I will submit a PR to upload zh_cn.lang
(good luck,23:19 ChongQing China)

**Comment by huneau** [comment]
what words ? I think, i do it on 9e00cf3
