### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by Shattered2909** [huneau/gregicality#7]
- [ ] Platinum Sludge Processing like in Bartworks (config option pls)
- [ ] A fixed Multi Smelter
- [x] Config Option for CEU conversion ratio (so I can make 1 EU turn into 2 RF but 4 RF into 1 EU)
- [ ] Power Storage Multiblock (unless that is already a thing)
- [x] Simple Ore Washer

**Comment by Shattered2909** [comment]
- [x] Config Option for removing Platinum/Iridium/Palladium/Osmium ores

**Comment by Shattered2909** [comment]
- [x] Remove Circuit Assembler recipes that take Molten Tin or Lead, no one uses those, Soldering Alloy is better

**Comment by hjae78** [comment]
- [ ] Either a config option for multiblock miners range, a new one with increased range or some way to boost the range of existing ones.

**Comment by huneau** [comment]
@hjae78, I can easily make it configurable, but Im not sure if I want that, what do you want exactly? I want a use case.

**Comment by hjae78** [comment]
I feel like 7x7 chunks is a little low for a machine at such high tier, maybe I'm underestimating how many ores are in a 7x7 area. A ZPM with 9x9 would be nice maybe.

**Comment by magcicada** [comment]
Can you merge this [mod](https://www.curseforge.com/minecraft/mc-mods/gregs-construct) into your project?

**Comment by huneau** [comment]
ok I can probably extend, its understandable

**Comment by huneau** [comment]
@magcicada it's already the case ?

**Comment by magcicada** [comment]
Blood Asp has made this attempt, and there are no problems in SoG, which can greatly expand the playability of TiC.

**Comment by magcicada** [comment]
https://github.com/Shadows-of-Fire/Shadows-of-Greg/commit/4c8c4cd7ee531198b4715fc54deb77eb14f839ab

**Comment by huneau** [comment]
My code comes from SoG, I swear it's in there

**Comment by hjae78** [comment]
Option to silktouch ores in miner. Maybe screwdriver to change mode?

**Comment by huneau** [comment]
I close this issue, and made smaller one
